package com.solar.common.context;

public enum ActionType {
	// DATA_UPLOAD, WORKING_MODE_UPDATE, GET_WORKING_MODE;

	CONNECT,
	REGIEST,
	FINDBACK,
	LOGIN,
	LOGOUT,
	EXIT,

	PROJECT_NEW,
	PROJECT_NEW_SUBMIT,
	PROJECT_UPDATE,
	PROJECT_DELETE,
	
	REGIEST_ADUIT_AGREE,
	REGIEST_ADUIT_REJECT,

	ACCOUNT_FINDBACK_ADUIT_AGREE,
	ACCOUNT_FINDBACK_ADUIT_REJECT,
	
	;
}
