package com.solar.common.context;

public enum ActionType {
	// DATA_UPLOAD, WORKING_MODE_UPDATE, GET_WORKING_MODE;

	CONNECT,
	REGIEST,
	FINDBACK,
	LOGIN,
	LOGOUT,
	EXIT,

	PROJECT_NEW,
	PROJECT_REFRESH,
	PROJECT_NEW_SUBMIT,
	PROJECT_CANCEL,
	PROJECT_UPDATE,
	PROJECT_UPDATE_SUBMIT,
	PROJECT_DELETE,

	REGIEST_ADUIT_AGREE,
	REGIEST_ADUIT_REJECT,

	ACCOUNT_FINDBACK_ADUIT_AGREE,
	ACCOUNT_FINDBACK_ADUIT_REJECT,

	WORKER_REFRESH,
	WORKER_CANCEL,
	WORKER_UPDATE,
	WORKER_UPDATE_SUBMIT,
	WORKER_FORBIDDEN,

	;
}
